# Generated by Django 4.2.5 on 2023-09-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_date',
            field=models.DateField(default='2023-09-23'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_date',
            field=models.DateField(default='2023-09-23'),
        ),
    ]
